{
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-prettier",
    "stylelint-prettier/recommended",
  ],
  "rules": {
    "no-empty-source": null,
    "declaration-empty-line-before": null,
    "no-missing-end-of-source-newline": null,
  }
}